### ISSUE TITLE
Improve the formulation of deck.yaml

### ISSUE THREAD

**Issue by ilyasst** [ets-lipec/consolidation-works#13]
Please provide a single PR for this issue.

Improve the `deck.yaml` structure according to this example: https://github.com/ilyasst/consolidation-works/blob/a8d9fa1282e4345383b1d4af668341a1b2698f82/TwoPlates.yaml

**Comment by arpcorrea** [comment]
done, PR https://github.com/ilyasst/consolidation-works/pull/7

**Comment by ilyasst** [comment]
Please refer to the appropriate commit or PR when marking an issue as done.

**Comment by arpcorrea** [comment]
done PR https://github.com/ilyasst/consolidation-works/pull/14
