### ISSUE TITLE
create fields from initial conditions

### ISSUE THREAD

**Issue by arpcorrea** [ets-lipec/consolidation-works#15]
By using the already-functional "mask" objected, fields will be created by multiplying "mask" by the initial field variable.
For example:
aux=0
for mesh_ in mesh.meshes:
   aux = mesh_.mask*mesh_.initial_temperature + aux
initial_temperature=aux

**Comment by arpcorrea** [comment]
done... PR https://github.com/ilyasst/consolidation-works/pull/7

**Comment by ilyasst** [comment]
Great ! Next step is the solver I believe, could you please create an issue for that ?

**Comment by arpcorrea** [comment]
Before solve, there is still one thing missing: Currently we have the boundary conditions values (temperature and Dic) for each edge on each domain, but not a Field itself... Remembering that if the shape of the problem is m x n, the "External temperature field" must be m+2 x n+2.

Also, Dic applies in a domain that is m x n and only at the interfaces. Thus, a field is still needed for this variable.

**Comment by ilyasst** [comment]
Could you then create an issue for this ?
