### ISSUE TITLE
The information printed by the code is meaningless

### ISSUE THREAD

**Issue by ilyasst** [ets-lipec/consolidation-works#7]
It seems that the `prints` in the code are mostly for debugging purposes. Please review the code and remove any useless prints. It would be good to provide the user with clearly written information during the code though, please add meaningful prints (in the future, https://docs.python.org/3/howto/logging.html should be used, let's keep that for https://github.com/ets-lipec/engine_consolidation).

**Comment by ilyasst** [comment]
Bump :wave:

**Comment by ilyasst** [comment]
Bump @arpcorrea

**Comment by arpcorrea** [comment]
done PR https://github.com/ilyasst/consolidation-works/pull/7
